#spring:
#  datasource:
#    username: root
#    password: root
#    url: service:mysql://192.168.0.109:3306/JAVA?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
#    driver-class-name: com.mysql.cj.service.Driver

server:
  port: 9090

spring:
  application:
    name: cowFat97



